### ISSUE TITLE
Error while parsing

### ISSUE THREAD

**Issue by maciejopalinski** [landalex/facebook-message-converter#1]
When i try to parse my data i get that error:

`Traceback (most recent call last):
  File ".\facebook-message-converter.py", line 23, in <module>
    message_datetime = datetime.fromtimestamp(int(message['timestamp']))
KeyError: 'timestamp'`

Please, help

**Comment by landalex** [comment]
I've just added some error handling in case the message doesn't have a timestamp for any reason. Grab the latest version of the script and give it a try :)

**Comment by maciejopalinski** [comment]
When I run script that error occured:

```
Traceback (most recent call last):
  File ".\facebook-message-converter.py", line 29, in <module>
    message_datetime = datetime.fromtimestamp(int(message['timestamp']))
KeyError: 'timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\facebook-message-converter.py", line 52, in <module>
    print(e, file=sys.stderr)
NameError: name 'sys' is not defined

```
I think that this script is dedicated to older format of facebook messages. Please, look at actual format and fix it bruh ;)

**Comment by landalex** [comment]
Can you provide a sample of what the new message format is?

**Comment by maciejopalinski** [comment]
[test.zip](https://github.com/landalex/facebook-message-converter/files/3801919/test.zip)
This is a file with example conversation in json. I don't know how the video or voice message is saved but you can just download your data from facebook and try it yourself

**Comment by landalex** [comment]
Thanks! I've pushed a change that tries to read `timestamp_ms` if it exists and parse that instead of relying on `timestamp`.

**Comment by maciejopalinski** [comment]
Thanks a lot! Your script works perfectly now
